### ISSUE TITLE
When start a test in SauceLabs with more than 3 browsers take forverer

### ISSUE THREAD

**Issue by cpanato** [yui/yeti#76]
I don't know if is an issue in yeti or in Sauce, open this here to check in Yeti, if not will open a ticket in saucelabs.

When run yeti with --caps with 3 or more browsers take much much time. if run with one or two is running smoothly

```
+ yeti --server --wd-url http://username:key@localhost:4445
Yeti Hub started. LAN: http://10.211.173.236:9000
                  Local: http://localhost:9000
Process leaked file descriptors. See http://wiki.jenkins-ci.org/display/JENKINS/Spawning+processes+from+build for more information
[workspace] $ /bin/sh -xe /tmp/hudson9170544525097097675.sh


+ yeti --junit --caps browserName=firefox;version=26;platform=Windows XP --caps browserName=internet explorer;version=10;platform=Windows 7 --caps browserName=internet explorer;version=9;platform=Windows 7 test-runner/test-runner.html

Waiting for Hub to launch browsers...
  Agent connected: Internet Explorer (10.0) / Windows 7 from 10.211.173.236
  Agent connected: Firefox (26.0) / Windows XP 64 from 10.211.173.236
```

two browsers show waiting for tests and one show closed waiting
![image](https://f.cloud.github.com/assets/4115580/2113679/716a621c-9030-11e3-8a35-0a3245faa647.png)

![image](https://f.cloud.github.com/assets/4115580/2113660/22b63b82-9030-11e3-8a9b-04ac86652be4.png)

**Comment by reid** [comment]
I can see from the screenshots that you're using Sauce Connect.

Due to a problem with the proxy used by Sauce Labs for IE 9, communication from IE 9 to Yeti does not work over Sauce Connect. This issue has been reported in #71.

I'm sorry you're having trouble. Thankfully, the root cause of #71 is understood and we just need to find the right solution. Please subscribe to that bug for updates. Thanks!

**Comment by cpanato** [comment]
@reid thanks will follow this issue and wait for that
thanks so much
durning this time will use just IE10 with FF and chrome
